import {
    Layers as Robot,
    Message as AIChatBot,
    Sort as WriteTitle,
    LeftAlign as WriteDescription,
    Tag as AudienceIdentifier,
} from "../components/icons";

const templates = [
    {
        id: "01",
        icon: <Robot />,
        link: "/template/define-campaign",
        slug: "define-campaign",
        name: "Definir Campaña",
        status: "active",
        api: "/content/definir_campana",
        description: "Define los objetivos de la campaña y detalles específicos.",
        customFields: [
            { label: "Nombre del Producto", type: "text", id: "nombreProducto", placeholder: "Introduce el nombre del producto" },
            { label: "Descripción del Producto", type: "textarea", id: "descripcionProducto", placeholder: "Describe el producto brevemente" },
            { label: "Tipo de Campaña", type: "text", id: "tipoCampana", placeholder: "Ej. Branding, Conversiones" },
            { label: "Duración Preferida", type: "text", id: "duracionPreferida", placeholder: "Ej. 30 días" },
        ],
    },
    {
        id: "02",
        icon: <AudienceIdentifier />,
        link: "/template/define-audience",
        slug: "define-audience",
        name: "Definir Público y Ubicaciones",
        status: "active",
        api: "/content/definir_publico_ubicaciones",
        description: "Identifica el público objetivo y las ubicaciones para la campaña.",
        customFields: [
            { label: "Nombre del Producto", type: "text", id: "nombreProducto", placeholder: "Introduce el nombre del producto" },
            { label: "Descripción del Producto", type: "textarea", id: "descripcionProducto", placeholder: "Describe el producto brevemente" },
            { label: "Distrito", type: "text", id: "distrito", placeholder: "Introduce el distrito" },
            { label: "Provincia", type: "text", id: "provincia", placeholder: "Introduce la provincia" },
            { label: "Departamento", type: "text", id: "departamento", placeholder: "Introduce el departamento" },
        ],
    },
    {
        id: "03",
        icon: <AIChatBot />,
        link: "/template/choose-format-cta",
        slug: "choose-format-cta",
        name: "Elegir Formato y CTA",
        status: "active",
        api: "/content/elegir_formato_cta",
        description: "Elige el formato de anuncio y la llamada a la acción (CTA).",
        customFields: [
            { label: "Nombre del Producto", type: "text", id: "nombreProducto", placeholder: "Introduce el nombre del producto" },
            { label: "Descripción del Producto", type: "textarea", id: "descripcionProducto", placeholder: "Describe el producto brevemente" },
        ],
    },
    {
        id: "04",
        icon: <WriteDescription />,
        link: "/template/create-creative-content",
        slug: "create-creative-content",
        name: "Crear Contenido Creativo",
        status: "active",
        api: "/content/crear_contenido_creativo",
        description: "Genera contenido creativo para anuncios publicitarios.",
        customFields: [
            { label: "Nombre del Producto", type: "text", id: "nombreProducto", placeholder: "Introduce el nombre del producto" },
            { label: "Descripción del Producto", type: "textarea", id: "descripcionProducto", placeholder: "Describe el producto brevemente" },
            { label: "Público Objetivo", type: "text", id: "publicoObjetivo", placeholder: "Ej. Jóvenes interesados en tecnología" },
            { label: "Tono/Estilo", type: "select", id: "tonoEstilo", options: ["Profesional", "Casual", "Divertido", "Emocionado"] },
        ],
    },
    {
        id: "05",
        icon: <WriteTitle />,
        link: "/template/create-heading",
        slug: "create-heading",
        name: "Generar Encabezados",
        status: "active",
        api: "/content/create_heading",
        description: "Genera encabezados efectivos para anuncios.",
        customFields: [
            { label: "Nombre del Producto", type: "text", id: "nombreProducto", placeholder: "Introduce el nombre del producto" },
            { label: "Descripción del Producto", type: "textarea", id: "descripcionProducto", placeholder: "Describe el producto brevemente" },
            { label: "Palabras Clave", type: "text", id: "palabrasClave", placeholder: "Ej. Tecnología, Innovación" },
            { label: "Estilo de Escritura", type: "select", id: "estiloEscritura", options: ["Formal", "Informal", "Creativo"] },
            { label: "Longitud Máxima", type: "number", id: "longitudMaxima", placeholder: "Ej. 100" },
            { label: "Variantes", type: "number", id: "variantes", placeholder: "Ej. 3" },
        ],
    },
];

export default templates;
